# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: babblesim
      url-base: https://github.com/BabbleSim

  group-filter: [-babblesim, -optional]

  #
  # Please add items below based on alphabetical order
  # zephyr-keep-sorted-start re(^\s+\- name:)
  projects:
    - name: acpica
      revision: 8d24867bc9c9d81c81eeac59391cda59333affd4
      path: modules/lib/acpica
    - name: cmsis
      revision: d1b8b20b6278615b00e136374540eb1c00dcabe7
      path: modules/hal/cmsis
      groups:
        - hal
    - name: cmsis-dsp
      revision: d80a49b2bb186317dc1db4ac88da49c0ab77e6e7
      path: modules/lib/cmsis-dsp
    - name: cmsis-nn
      revision: e9328d612ea3ea7d0d210d3ac16ea8667c01abdd
      path: modules/lib/cmsis-nn
    - name: cmsis_6
      repo-path: CMSIS_6
      revision: 783317a3072554acbac86cca2ff24928cbf98d30
      path: modules/lib/cmsis_6
    - name: edtt
      revision: b9ca3c7030518f07b7937dacf970d37a47865a76
      path: tools/edtt
      groups:
        - tools
    - name: fatfs
      revision: 16245c7c41d2b79e74984f49b5202551786b8a9b
      path: modules/fs/fatfs
      groups:
        - fs
    - name: hal_microchip
      revision: fa2431a906ffb560160d40739d7cf04169551103
      path: modules/hal/microchip
      groups:
        - hal
    - name: hal_nordic
      revision: 37ca068d7b013fb65a2acc9306bffa48a3e72839
      path: modules/hal/nordic
      groups:
        - hal
    - name: hal_rpi_pico
      path: modules/hal/rpi_pico
      revision: 7b57b24588797e6e7bf18b6bda168e6b96374264
      groups:
        - hal
    - name: hal_silabs
      revision: 8a173e9e566a396a19d18da4661cb54ce098f268
      path: modules/hal/silabs
      groups:
        - hal
    - name: hal_st
      revision: 05fd4533730a9aea845261c5d24ed9832a6f0b6e
      path: modules/hal/st
      groups:
        - hal
    - name: hal_stm32
      revision: 55043bcc35fffa3b4a8c75a696d932b5020aad09
      path: modules/hal/stm32
      groups:
        - hal
    - name: hal_tdk
      revision: 6727477af1e46fa43878102489b9672a9d24e39f
      path: modules/hal/tdk
      groups:
        - hal
    - name: hal_wurthelektronik
      revision: e3e2797b224fc48fdef1bc3e5a12a7c73108bba2
      path: modules/hal/wurthelektronik
      groups:
        - hal
    - name: hostap
      path: modules/lib/hostap
      revision: 697fd2cf5cbbd0c5375fc34761b6a9d7489a67d2
    - name: liblc3
      revision: 48bbd3eacd36e99a57317a0a4867002e0b09e183
      path: modules/lib/liblc3
    - name: libmctp
      revision: b97860e78998551af99931ece149eeffc538bdb1
      path: modules/lib/libmctp
    - name: libmetal
      revision: 3e8781aae9d7285203118c05bc01d4eb0ca565a7
      path: modules/hal/libmetal
      groups:
        - hal
    - name: littlefs
      path: modules/fs/littlefs
      groups:
        - fs
      revision: ed0531d59ee37f5fb2762bcf2fc8ba4efaf82656
    - name: loramac-node
      revision: fb00b383072518c918e2258b0916c996f2d4eebe
      path: modules/lib/loramac-node
    - name: lvgl
      revision: 1ed1ddd881c3784049a92bb9fe37c38c6c74d998
      path: modules/lib/gui/lvgl
    - name: mbedtls
      revision: 4952e1328529ee549d412b498ea71c54f30aa3b1
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      revision: 346f7374ff4467e40b5594658f8ac67a5e9813c9
      path: bootloader/mcuboot
      groups:
        - bootloader
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      groups:
        - debug
      revision: 33e5c23cbedda5ba12dbe50c4baefb362a791001
    - name: net-tools
      revision: 93acc8bac4661e74e695eb1aea94c7c5262db2e2
      path: tools/net-tools
      groups:
        - tools
    - name: nrf_hw_models
      revision: 73a5d5827a94820be65b7d276d28173ec10bab9f
      path: modules/bsim_hw_models/nrf_hw_models
    - name: nrf_wifi
      revision: e35f707a782b7c4c0eb83a3b06ca4e6eb693f29f
      path: modules/lib/nrf_wifi
    - name: open-amp
      revision: 52bb1783521c62c019451cee9b05b8eda9d7425f
      path: modules/lib/open-amp
    - name: openthread
      revision: 3ae741f95e7dfb391dec35c48742862049eb62e8
      path: modules/lib/openthread
    - name: percepio
      path: modules/debug/percepio
      revision: 49e6dc202aa38c2a3edbafcc2dab85dec6aee973
      groups:
        - debug
    - name: picolibc
      path: modules/lib/picolibc
      revision: 82d62ed1ac55b4e34a12d0390aced2dc9af13fc9
    - name: segger
      revision: cf56b1d9c80f81a26e2ac5727c9cf177116a4692
      path: modules/debug/segger
      groups:
        - debug
    - name: tinycrypt
      revision: 1012a3ebee18c15ede5efc8332ee2fc37817670f
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: trusted-firmware-a
      revision: 713ffbf96c5bcbdeab757423f10f73eb304eff07
      path: modules/tee/tf-a/trusted-firmware-a
      groups:
        - tee
    - name: trusted-firmware-m
      revision: 918f32d9fce5e0ee59fc33844b5317b7626ce37a
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: uoscore-uedhoc
      revision: 54abc109c9c0adfd53c70077744c14e454f04f4a
      path: modules/lib/uoscore-uedhoc
    - name: zcbor
      revision: 9b07780aca6fb21f82a241ba386ad9b379809337
      path: modules/lib/zcbor
  # zephyr-keep-sorted-stop

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
