# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: babblesim
      url-base: https://github.com/BabbleSim

  group-filter: [-babblesim, -optional]

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: modules/hal/cmsis
      groups:
        - hal
    - name: cmsis-dsp
      revision: 6489e771e9c405f1763b52d64a3f17a1ec488ace
      path: modules/lib/cmsis-dsp
    - name: cmsis-nn
      revision: 0c8669d81381ccf3b1a01d699f3b68b50134a99f
      path: modules/lib/cmsis-nn
    - name: edtt
      revision: 64e5105ad82390164fb73fc654be3f73a608209a
      path: tools/edtt
      groups:
        - tools
    - name: fatfs
      revision: 427159bf95ea49b7680facffaa29ad506b42709b
      path: modules/fs/fatfs
      groups:
        - fs
    - name: hal_espressif
      revision: 67fa60bdffca7ba8ed199aecfaa26f485f24878b
      path: modules/hal/espressif
      west-commands: west/west-commands.yml
      groups:
        - hal
    - name: hal_rpi_pico
      path: modules/hal/rpi_pico
      revision: fba7162cc7bee06d0149622bbcaac4e41062d368
      groups:
        - hal
    - name: hal_st
      revision: 0643d20ae85b32c658ad11036f7c964a860ddefe
      path: modules/hal/st
      groups:
        - hal
    - name: hal_stm32
      revision: 60c9634f61c697e1c310ec648d33529712806069
      path: modules/hal/stm32
      groups:
        - hal
    - name: hal_ti
      revision: b85f86e51fc4d47c4c383d320d64d52d4d371ae4
      path: modules/hal/ti
      groups:
        - hal
    - name: hostap
      repo-path: hostap
      path: modules/lib/hostap
      revision: dee924caf7218d0ee2c2698c217559b1292a46d0
    - name: libmetal
      revision: 243eed541b9c211a2ce8841c788e62ddce84425e
      path: modules/hal/libmetal
      groups:
        - hal
    - name: liblc3
      revision: 1a5938ebaca4f13fe79ce074f5dee079783aa29f
      path: modules/lib/liblc3
    - name: littlefs
      path: modules/fs/littlefs
      groups:
        - fs
      revision: 408c16a909dd6cf128874a76f21c793798c9e423
    - name: loramac-node
      revision: 842413c5fb98707eb5f26e619e8e792453877897
      path: modules/lib/loramac-node
    - name: lvgl
      revision: 2b76c641749725ac90c6ac7959ca7718804cf356
      path: modules/lib/gui/lvgl
    - name: mbedtls
      revision: 6ec4abdcda78dfc47315af568f93e5ad4398dea0
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      revision: a4eda30f5b0cfd0cf15512be9dcd559239dbfc91
      path: bootloader/mcuboot
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      groups:
        - debug
      revision: a819419603a2dfcb47f7f39092e1bc112e45d1ef
    - name: net-tools
      revision: 3a677d355cc7f73e444801a6280d0ccec80a1957
      path: tools/net-tools
      groups:
        - tools
    - name: nrf_hw_models
      revision: 52d0b4b7b7431d8da6222cc3b17a8afdcb099baf
      path: modules/bsim_hw_models/nrf_hw_models
    - name: open-amp
      revision: da78aea63159771956fe0c9263f2e6985b66e9d5
      path: modules/lib/open-amp
    - name: openthread
      revision: 7761b81d23b10b3d5ee21b8504c67535cde10896
      path: modules/lib/openthread
    - name: percepio
      path: modules/debug/percepio
      revision: 0fbc5b72aeab8a6434523a3a7bc8111c17f0bc73
      groups:
        - debug
    - name: picolibc
      path: modules/lib/picolibc
      revision: 764ef4e401a8f4c6a86ab723533841f072885a5b
    - name: segger
      revision: 9d0191285956cef43daf411edc2f1a7788346def
      path: modules/debug/segger
      groups:
        - debug
    - name: tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: trusted-firmware-m
      revision: 0b898c9b72171b0a260c0bb64a92ea4713f9e931
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: trusted-firmware-a
      revision: 421dc050278287839f5c70019bd6aec617f2bbdb
      path: modules/tee/tf-a/trusted-firmware-a
      groups:
        - tee
    - name: uoscore-uedhoc
      revision: 150f4eb2955eaf36ac0f9519d4f4f58d5ade5740
      path: modules/lib/uoscore-uedhoc
    - name: zcbor
      revision: d3093b5684f62268c7f27f8a5079f166772619de
      path: modules/lib/zcbor

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
