# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: babblesim
      url-base: https://github.com/BabbleSim

  group-filter: [-babblesim, -optional]

  #
  # Please add items below based on alphabetical order
  projects:
    - name: acpica
      revision: 8d24867bc9c9d81c81eeac59391cda59333affd4
      path: modules/lib/acpica
    - name: cmsis
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: modules/hal/cmsis
      groups:
        - hal
    - name: cmsis-dsp
      revision: 6489e771e9c405f1763b52d64a3f17a1ec488ace
      path: modules/lib/cmsis-dsp
    - name: cmsis-nn
      revision: ea987c1ca661be723de83bd159aed815d6cbd430
      path: modules/lib/cmsis-nn
    - name: edtt
      revision: 8d7b543d4d2f2be0f78481e4e1d8d73a88024803
      path: tools/edtt
      groups:
        - tools
    - name: fatfs
      revision: 427159bf95ea49b7680facffaa29ad506b42709b
      path: modules/fs/fatfs
      groups:
        - fs
    - name: hal_espressif
      revision: 87e7902d7184a8280b4d13bce79801a723f4ddd8
      path: modules/hal/espressif
      west-commands: west/west-commands.yml
      groups:
        - hal
    - name: hal_nordic
      revision: ab5cb2e2faeb1edfad7a25286dcb513929ae55da
      path: modules/hal/nordic
      groups:
        - hal
    - name: hal_rpi_pico
      path: modules/hal/rpi_pico
      revision: fba7162cc7bee06d0149622bbcaac4e41062d368
      groups:
        - hal
    - name: hal_silabs
      revision: a09dd1b82b24aa3060e162c0dfa40026c0dba450
      path: modules/hal/silabs
      groups:
        - hal
    - name: hal_st
      revision: b77157f6bc4395e398d90ab02a7d2cbc01ab2ce7
      path: modules/hal/st
      groups:
        - hal
    - name: hal_stm32
      revision: f1317150eac951fdd8259337a47cbbc4c2e6d335
      path: modules/hal/stm32
      groups:
        - hal
    - name: hal_telink
      revision: 4226c7fc17d5a34e557d026d428fc766191a0800
      path: modules/hal/telink
      groups:
        - hal
    - name: hal_ti
      revision: b85f86e51fc4d47c4c383d320d64d52d4d371ae4
      path: modules/hal/ti
      groups:
        - hal
    - name: hal_wurthelektronik
      revision: e5bcb2eac1bb9639ce13b4dafc78eb254e014342
      path: modules/hal/wurthelektronik
      groups:
        - hal
    - name: hal_xtensa
      revision: a2d658525b16c57bea8dd565f5bd5167e4b9f1ee
      path: modules/hal/xtensa
      groups:
        - hal
    - name: hostap
      repo-path: hostap
      path: modules/lib/hostap
      revision: a90df86d7c596a5367ff70c2b50c7f599e6636f3
    - name: libmetal
      revision: a6851ba6dba8c9e87d00c42f171a822f7a29639b
      path: modules/hal/libmetal
      groups:
        - hal
    - name: liblc3
      revision: 1a5938ebaca4f13fe79ce074f5dee079783aa29f
      path: modules/lib/liblc3
    - name: littlefs
      path: modules/fs/littlefs
      groups:
        - fs
      revision: 408c16a909dd6cf128874a76f21c793798c9e423
    - name: loramac-node
      revision: fb00b383072518c918e2258b0916c996f2d4eebe
      path: modules/lib/loramac-node
    - name: lvgl
      revision: 2b498e6f36d6b82ae1da12c8b7742e318624ecf5
      path: modules/lib/gui/lvgl
    - name: mbedtls
      revision: 2f24831ee13d399ce019c4632b0bcd440a713f7c
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      revision: fb2cf0ec3da3687b93f28e556ab682bdd4b85223
      path: bootloader/mcuboot
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      groups:
        - debug
      revision: 71ace1f5caa03e56c8740a09863e685efb4b2360
    - name: net-tools
      revision: 7c7a856814d7f27509c8511fef14cec21f7d0c30
      path: tools/net-tools
      groups:
        - tools
    - name: nrf_hw_models
      revision: 6c389b9b5fa0a079cd4502e69d375da4c0c289b7
      path: modules/bsim_hw_models/nrf_hw_models
    - name: open-amp
      revision: 76d2168bcdfcd23a9a7dce8c21f2083b90a1e60a
      path: modules/lib/open-amp
    - name: openthread
      revision: 3873c6fcd5a8a9dd01b71e8efe32ef5dc7923bb1
      path: modules/lib/openthread
    - name: percepio
      path: modules/debug/percepio
      revision: a49e5f3947faad0dd654eddd5a750127fb81e50d
      groups:
        - debug
    - name: picolibc
      path: modules/lib/picolibc
      revision: 764ef4e401a8f4c6a86ab723533841f072885a5b
    - name: segger
      revision: b011c45b585e097d95d9cf93edf4f2e01588d3cd
      path: modules/debug/segger
      groups:
        - debug
    - name: tinycrypt
      revision: 1012a3ebee18c15ede5efc8332ee2fc37817670f
      path: modules/crypto/tinycrypt
      groups:
        - crypto
    - name: trusted-firmware-m
      revision: 069455be098383bf96eab73e3ff8e0c66c60fa5a
      path: modules/tee/tf-m/trusted-firmware-m
      groups:
        - tee
    - name: trusted-firmware-a
      revision: 713ffbf96c5bcbdeab757423f10f73eb304eff07
      path: modules/tee/tf-a/trusted-firmware-a
      groups:
        - tee
    - name: uoscore-uedhoc
      revision: 84ef879a46d7bfd9a423fbfb502b04289861f9ea
      path: modules/lib/uoscore-uedhoc
    - name: zcbor
      revision: 75d088037eb237b18e7ec1f47c9ce494b9b95aab
      path: modules/lib/zcbor

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
